/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'NotFoundPage': RouteRecordInfo<
      'NotFoundPage',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'demo': RouteRecordInfo<
      'demo',
      '/demo',
      Record<never, never>,
      Record<never, never>,
      | '/demo/button'
      | '/demo/custom-theme'
      | '/demo/custom-theme/table'
      | '/demo/form'
      | '/demo/provider/naive'
      | '/demo/provider/unocss'
      | 'IconDemo'
      | 'LayoutDemo'
      | 'ProviderDemo'
      | 'SearchFormDemo'
      | 'TableDemo'
      | 'UploadDemo'
    >,
    '/demo/button': RouteRecordInfo<
      '/demo/button',
      '/demo/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/custom-theme': RouteRecordInfo<
      '/demo/custom-theme',
      '/demo/custom-theme',
      Record<never, never>,
      Record<never, never>,
      | '/demo/custom-theme/table'
    >,
    '/demo/custom-theme/table': RouteRecordInfo<
      '/demo/custom-theme/table',
      '/demo/custom-theme/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/form': RouteRecordInfo<
      '/demo/form',
      '/demo/form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'IconDemo': RouteRecordInfo<
      'IconDemo',
      '/demo/icon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LayoutDemo': RouteRecordInfo<
      'LayoutDemo',
      '/demo/layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ProviderDemo': RouteRecordInfo<
      'ProviderDemo',
      '/demo/provider',
      Record<never, never>,
      Record<never, never>,
      | '/demo/provider/naive'
      | '/demo/provider/unocss'
    >,
    '/demo/provider/naive': RouteRecordInfo<
      '/demo/provider/naive',
      '/demo/provider/naive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo/provider/unocss': RouteRecordInfo<
      '/demo/provider/unocss',
      '/demo/provider/unocss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'SearchFormDemo': RouteRecordInfo<
      'SearchFormDemo',
      '/demo/search-form',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'TableDemo': RouteRecordInfo<
      'TableDemo',
      '/demo/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'UploadDemo': RouteRecordInfo<
      'UploadDemo',
      '/demo/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'DynamicExample': RouteRecordInfo<
      'DynamicExample',
      '/dynamic-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'HomePage': RouteRecordInfo<
      'HomePage',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'manage': RouteRecordInfo<
      'manage',
      '/manage',
      Record<never, never>,
      Record<never, never>,
      | 'ManageMenu'
      | 'ManageRole'
      | 'ManageUser'
    >,
    'ManageMenu': RouteRecordInfo<
      'ManageMenu',
      '/manage/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ManageRole': RouteRecordInfo<
      'ManageRole',
      '/manage/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ManageUser': RouteRecordInfo<
      'ManageUser',
      '/manage/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'test': RouteRecordInfo<
      'test',
      '/test',
      Record<never, never>,
      Record<never, never>,
      | '/test/layout'
      | '/test/layout/blank'
      | '/test/layout/side-group-menu'
      | '/test/layout/side-menu'
      | '/test/layout/side-menu-2'
      | '/test/layout/side-mixed-menu'
      | '/test/layout/top-group-menu-2'
      | '/test/layout/top-menu'
      | '/test/layout/top-menu-2'
      | '/test/layout/top-mixed-menu-2'
      | '/test/link'
      | '/test/page-1/'
      | '/test/page-1/[id]'
      | '/test/page-2/'
      | '/test/page-3/page-4/page-4'
      | '/test/page-3/page-4/page-5'
    >,
    '/test/layout': RouteRecordInfo<
      '/test/layout',
      '/test/layout',
      Record<never, never>,
      Record<never, never>,
      | '/test/layout/blank'
      | '/test/layout/side-group-menu'
      | '/test/layout/side-menu'
      | '/test/layout/side-menu-2'
      | '/test/layout/side-mixed-menu'
      | '/test/layout/top-group-menu-2'
      | '/test/layout/top-menu'
      | '/test/layout/top-menu-2'
      | '/test/layout/top-mixed-menu-2'
    >,
    '/test/layout/blank': RouteRecordInfo<
      '/test/layout/blank',
      '/test/layout/blank',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/side-group-menu': RouteRecordInfo<
      '/test/layout/side-group-menu',
      '/test/layout/side-group-menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/side-menu': RouteRecordInfo<
      '/test/layout/side-menu',
      '/test/layout/side-menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/side-menu-2': RouteRecordInfo<
      '/test/layout/side-menu-2',
      '/test/layout/side-menu-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/side-mixed-menu': RouteRecordInfo<
      '/test/layout/side-mixed-menu',
      '/test/layout/side-mixed-menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/top-group-menu-2': RouteRecordInfo<
      '/test/layout/top-group-menu-2',
      '/test/layout/top-group-menu-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/top-menu': RouteRecordInfo<
      '/test/layout/top-menu',
      '/test/layout/top-menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/top-menu-2': RouteRecordInfo<
      '/test/layout/top-menu-2',
      '/test/layout/top-menu-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/layout/top-mixed-menu-2': RouteRecordInfo<
      '/test/layout/top-mixed-menu-2',
      '/test/layout/top-mixed-menu-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/link': RouteRecordInfo<
      '/test/link',
      '/test/link',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/page-1/': RouteRecordInfo<
      '/test/page-1/',
      '/test/page-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/page-1/[id]': RouteRecordInfo<
      '/test/page-1/[id]',
      '/test/page-1/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/test/page-2/': RouteRecordInfo<
      '/test/page-2/',
      '/test/page-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/page-3/page-4/page-4': RouteRecordInfo<
      '/test/page-3/page-4/page-4',
      '/test/page-3/page-4/page-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/page-3/page-4/page-5': RouteRecordInfo<
      '/test/page-3/page-4/page-5',
      '/test/page-3/page-4/page-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/404.page.vue': {
      routes:
        | 'NotFoundPage'
      views:
        | never
    }
    'src/pages/demo.meta.vue': {
      routes:
        | '/demo/button'
        | '/demo/custom-theme'
        | '/demo/custom-theme/table'
        | '/demo/form'
        | '/demo/provider/naive'
        | '/demo/provider/unocss'
        | 'IconDemo'
        | 'LayoutDemo'
        | 'ProviderDemo'
        | 'SearchFormDemo'
        | 'TableDemo'
        | 'UploadDemo'
        | 'demo'
      views:
        | 'default'
    }
    'src/pages/demo/button.page.vue': {
      routes:
        | '/demo/button'
      views:
        | never
    }
    'src/pages/demo/custom-theme.meta.vue': {
      routes:
        | '/demo/custom-theme'
        | '/demo/custom-theme/table'
      views:
        | 'default'
    }
    'src/pages/demo/custom-theme/table.page.vue': {
      routes:
        | '/demo/custom-theme/table'
      views:
        | never
    }
    'src/pages/demo/form.page.vue': {
      routes:
        | '/demo/form'
      views:
        | never
    }
    'src/pages/demo/icon.page.vue': {
      routes:
        | 'IconDemo'
      views:
        | never
    }
    'src/pages/demo/layout.page.vue': {
      routes:
        | 'LayoutDemo'
      views:
        | never
    }
    'src/pages/demo/provider.meta.vue': {
      routes:
        | '/demo/provider/naive'
        | '/demo/provider/unocss'
        | 'ProviderDemo'
      views:
        | 'default'
    }
    'src/pages/demo/provider/naive.page.vue': {
      routes:
        | '/demo/provider/naive'
      views:
        | never
    }
    'src/pages/demo/provider/unocss.page.vue': {
      routes:
        | '/demo/provider/unocss'
      views:
        | never
    }
    'src/pages/demo/search-form.page.vue': {
      routes:
        | 'SearchFormDemo'
      views:
        | never
    }
    'src/pages/demo/table.page.vue': {
      routes:
        | 'TableDemo'
      views:
        | never
    }
    'src/pages/demo/upload.page.vue': {
      routes:
        | 'UploadDemo'
      views:
        | never
    }
    'src/pages/dynamic-example.page.vue': {
      routes:
        | 'DynamicExample'
      views:
        | never
    }
    'src/pages/home.page.vue': {
      routes:
        | 'HomePage'
      views:
        | never
    }
    'src/pages/manage.meta.vue': {
      routes:
        | 'ManageMenu'
        | 'ManageRole'
        | 'ManageUser'
        | 'manage'
      views:
        | 'default'
    }
    'src/pages/manage/menu.page.vue': {
      routes:
        | 'ManageMenu'
      views:
        | never
    }
    'src/pages/manage/role.page.vue': {
      routes:
        | 'ManageRole'
      views:
        | never
    }
    'src/pages/manage/user.page.vue': {
      routes:
        | 'ManageUser'
      views:
        | never
    }
    'src/pages/test.meta.vue': {
      routes:
        | '/test/layout'
        | '/test/layout/blank'
        | '/test/layout/side-group-menu'
        | '/test/layout/side-menu'
        | '/test/layout/side-menu-2'
        | '/test/layout/side-mixed-menu'
        | '/test/layout/top-group-menu-2'
        | '/test/layout/top-menu'
        | '/test/layout/top-menu-2'
        | '/test/layout/top-mixed-menu-2'
        | '/test/link'
        | '/test/page-1/'
        | '/test/page-1/[id]'
        | '/test/page-2/'
        | '/test/page-3/page-4/page-4'
        | '/test/page-3/page-4/page-5'
        | 'test'
      views:
        | 'default'
    }
    'src/pages/test/layout.page.vue': {
      routes:
        | '/test/layout'
        | '/test/layout/blank'
        | '/test/layout/side-group-menu'
        | '/test/layout/side-menu'
        | '/test/layout/side-menu-2'
        | '/test/layout/side-mixed-menu'
        | '/test/layout/top-group-menu-2'
        | '/test/layout/top-menu'
        | '/test/layout/top-menu-2'
        | '/test/layout/top-mixed-menu-2'
      views:
        | 'default'
    }
    'src/pages/test/layout/blank.page.vue': {
      routes:
        | '/test/layout/blank'
      views:
        | never
    }
    'src/pages/test/layout/side-group-menu.page.vue': {
      routes:
        | '/test/layout/side-group-menu'
      views:
        | never
    }
    'src/pages/test/layout/side-menu.page.vue': {
      routes:
        | '/test/layout/side-menu'
      views:
        | never
    }
    'src/pages/test/layout/side-menu-2.page.vue': {
      routes:
        | '/test/layout/side-menu-2'
      views:
        | never
    }
    'src/pages/test/layout/side-mixed-menu.page.vue': {
      routes:
        | '/test/layout/side-mixed-menu'
      views:
        | never
    }
    'src/pages/test/layout/top-group-menu-2.page.vue': {
      routes:
        | '/test/layout/top-group-menu-2'
      views:
        | never
    }
    'src/pages/test/layout/top-menu.page.vue': {
      routes:
        | '/test/layout/top-menu'
      views:
        | never
    }
    'src/pages/test/layout/top-menu-2.page.vue': {
      routes:
        | '/test/layout/top-menu-2'
      views:
        | never
    }
    'src/pages/test/layout/top-mixed-menu-2.page.vue': {
      routes:
        | '/test/layout/top-mixed-menu-2'
      views:
        | never
    }
    'src/pages/test/link.link.vue': {
      routes:
        | '/test/link'
      views:
        | never
    }
    'src/pages/test/page-1/index.page.vue': {
      routes:
        | '/test/page-1/'
      views:
        | never
    }
    'src/pages/test/page-1/[id].page.vue': {
      routes:
        | '/test/page-1/[id]'
      views:
        | never
    }
    'src/pages/test/page-2/index.page.vue': {
      routes:
        | '/test/page-2/'
      views:
        | never
    }
    'src/pages/test/page-3/page-4/page-4.page.vue': {
      routes:
        | '/test/page-3/page-4/page-4'
      views:
        | never
    }
    'src/pages/test/page-3/page-4/page-5.page.vue': {
      routes:
        | '/test/page-3/page-4/page-5'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
